env:
  BUCKET_NAME: 'agoric-snapshots-public'
  PROJECT_ID: 60745596728

jobs:
  create-snapshot:
    if: ${{ github.event.pull_request.merged }} == 'true'
    name: Create Mainfork Snapshot
    permissions:
      contents: read
      id-token: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - id: get-proposal-count-difference
        name: Get Proposals Count Difference
        run: |
          #! /bin/bash
          set -o errexit -o errtrace -o xtrace

          CURRENT_BRANCH="$(git branch --show-current)"
          MERGE_COMMIT="${{ github.event.pull_request.merge_commit_sha }}"
          PRE_MERGE_COMMIT="$(git rev-parse "$MERGE_COMMIT^1")"

          get_number_of_proposals() {
            find '.' -maxdepth 1 -mindepth 1 -type d | \
            while read directory
            do
                if find "$directory" -type f | grep --silent .
                then
                    echo "$directory"
                fi
            done |
            wc --lines
          }

          current_count="$(get_number_of_proposals)"
          git checkout "$PRE_MERGE_COMMIT" --detach
          previous_count="$(get_number_of_proposals)"
          git checkout "$CURRENT_BRANCH"

          echo "DIFFERENCE=$((current_count - previous_count))" >> $GITHUB_OUTPUT
        working-directory: proposals

name: Create Mainfork Snapshot

on:
  pull_request:
    branches:
      - main
    types:
      - closed
